# Baremetal application Makefile
DEMO_DIR := $(subst Makefile,.,$(lastword $(MAKEFILE_LIST)))

APP     = interrupts-simple
SOURCES = $(DEMO_DIR)/src/interrupts-simple.c

include $(DEMO_DIR)/../../share/app.mk
