# Baremetal application Makefile
DEMO_DIR := $(subst Makefile,.,$(lastword $(MAKEFILE_LIST)))

APP     = exception-demo
SOURCES = $(DEMO_DIR)/src/exception-demo.c

include $(DEMO_DIR)/../../share/app.mk
