# ----[ PLATFORM CONFIGURATION ]----

CONFIG_PROCESSOR            = L31
CONFIG_PLATFORM             = Inferno

#CONFIG_ENVIRONMENT         ?= FPGA_SEMIHOSTING
#CONFIG_ENVIRONMENT         ?= FPGA_UART
#CONFIG_ENVIRONMENT         ?= SIMULATOR

# ----[ CORE CONFIGURATION ]----

CONFIG_CORE_FREQ            ?= 25
CONFIG_HAS_FPU              = Y
CONFIG_HAS_PMP              = Y
CONFIG_PMP_NUM_REGIONS      = 16
CONFIG_HAS_TCMS             = Y
CONFIG_HAS_CACHES           = Y
CONFIG_PIC_NUM_INTERRUPTS   = 128
CONFIG_HAS_HPM              = Y
