# ----[ PLATFORM CONFIGURATION ]----

CONFIG_PROCESSOR            = L150
CONFIG_PLATFORM             = Hobbs

#CONFIG_ENVIRONMENT         ?= FPGA_SEMIHOSTING
#CONFIG_ENVIRONMENT         ?= FPGA_UART

# ----[ CORE CONFIGURATION ]----

CONFIG_CORE_FREQ            ?= 50
CONFIG_CLIC_NUM_INTERRUPTS  = 16
CONFIG_CLIC_INTCTLBITS      = 3

# ----[ PLATFORM CONFIGURATION ]----

CONFIG_PLIC                 = N
CONFIG_SECURITY             = N
CONFIG_TSBL                 = Y
