# ----[ PLATFORM CONFIGURATION ]----

CONFIG_PROCESSOR            = L31
CONFIG_PLATFORM             = Inferno

#CONFIG_ENVIRONMENT         ?= FPGA_SEMIHOSTING
#CONFIG_ENVIRONMENT         ?= FPGA_UART
#CONFIG_ENVIRONMENT         ?= SIMULATOR

# ----[ CORE CONFIGURATION ]----

CONFIG_CORE_FREQ            ?= 25
CONFIG_HAS_FPU              = N
CONFIG_HAS_TCMS             = N
CONFIG_HAS_CACHES           = Y
CONFIG_PIC_NUM_INTERRUPTS   = 32
CONFIG_HAS_HPM              = N
